# Generated by Django 5.2.9 on 2025-12-06 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('md5_hash', models.CharField(blank=True, max_length=32)),
                ('sha1_hash', models.CharField(blank=True, max_length=40)),
                ('sha256_hash', models.CharField(blank=True, max_length=64)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yara_filtered_matches', models.JSONField(blank=True, default=list)),
                ('yara_raw_matches', models.JSONField(blank=True, default=list)),
                ('yara_error', models.TextField(blank=True, null=True)),
                ('bazaar_success', models.BooleanField(default=False)),
                ('bazaar_is_malicious', models.BooleanField(default=False)),
                ('bazaar_malware_info', models.JSONField(blank=True, default=dict)),
                ('bazaar_error', models.TextField(blank=True, null=True)),
                ('lstm_final_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('lstm_max_prob_anomaly', models.FloatField(blank=True, null=True)),
                ('lstm_mean_prob_anomaly', models.FloatField(blank=True, null=True)),
                ('lstm_num_windows', models.IntegerField(blank=True, null=True)),
                ('lstm_error', models.TextField(blank=True, null=True)),
                ('interpreter', models.CharField(blank=True, max_length=100, null=True)),
                ('vm_log_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='analysis.uploadedfile')),
            ],
        ),
    ]
