# Generated by Django 5.2.9 on 2025-12-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_analysisresult_bazaar_malware_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_path',
            field=models.FileField(default=1.0, max_length=500, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='uploadedfile',
            table='uploaded_files',
        ),
        migrations.CreateModel(
            name='ResultAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interpreter', models.CharField(blank=True, max_length=100, null=True)),
                ('vm_log_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='analysis.uploadedfile')),
            ],
            options={
                'db_table': 'result_analysis',
            },
        ),
        migrations.CreateModel(
            name='LstmAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anomalous', models.BooleanField(default=False, null=True)),
                ('final_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('max_prob_anomaly', models.FloatField(blank=True, null=True)),
                ('mean_prob_anomaly', models.FloatField(blank=True, null=True)),
                ('num_windows', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('result_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lstm_analysis', to='analysis.resultanalysis')),
            ],
            options={
                'db_table': 'lstm_analysis',
            },
        ),
        migrations.CreateModel(
            name='BazaarAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_malicious', models.BooleanField(default=False)),
                ('malware_info', models.JSONField(blank=True, default=dict, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('result_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bazaar_analysis', to='analysis.resultanalysis')),
            ],
            options={
                'db_table': 'bazaar_analysis',
            },
        ),
        migrations.CreateModel(
            name='YaraAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.JSONField(blank=True, default=list)),
                ('raw_matches', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, null=True)),
                ('result_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yara_analysis', to='analysis.resultanalysis')),
            ],
            options={
                'db_table': 'yara_analysis',
            },
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
    ]
